import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ChevronRight, Clock, Play, Eye, Heart, Bookmark, Crown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useNavigate } from 'react-router-dom';
export default function RankingSection({ posts }) {
    const navigate = useNavigate();
    const handleCreatorClick = (display_name) => {
        navigate(`/account/profile?display_name=${display_name}`);
    };
    const handlePostClick = (post) => {
        navigate(`/post/detail?post_id=${post.id}`);
    };
    return (_jsx("section", { className: "bg-white py-6 border-t border-gray-200", children: _jsxs("div", { className: "max-w-screen-md mx-auto px-4 sm:px-6 lg:px-8 py-4", children: [_jsxs("div", { className: "flex items-center justify-between mb-6", children: [_jsx("h2", { className: "text-xl font-bold text-gray-900", children: "\u30E9\u30F3\u30AD\u30F3\u30B0" }), _jsxs(Button, { variant: "ghost", size: "sm", className: "text-primary hover:text-primary", children: ["\u3082\u3063\u3068\u898B\u308B", _jsx(ChevronRight, { className: "h-4 w-4 ml-1" })] })] }), _jsx("div", { className: "grid grid-cols-2 gap-1", children: posts.map((post) => (_jsxs("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition-shadow", children: [_jsxs("div", { className: "relative", onClick: () => handlePostClick(post), children: [_jsx("img", { src: post.thumbnail, alt: post.title, className: "w-full aspect-square object-cover", onClick: () => handlePostClick(post) }), _jsxs("div", { className: "absolute top-2 left-2 bg-primary text-white text-xs font-bold px-2 py-1 rounded flex items-center", children: [post.rank === 1 && _jsx(Crown, { className: "h-3 w-3 mr-1" }), "#", post.rank] }), _jsxs("div", { className: "absolute bottom-2 right-2 bg-black bg-opacity-70 text-white text-xs px-2 py-1 rounded flex items-center", children: [_jsx(Clock, { className: "h-3 w-3 mr-1" }), post.duration] }), _jsx("div", { className: "absolute inset-0 flex items-center justify-center opacity-0 hover:opacity-100 transition-opacity bg-black bg-opacity-30", children: _jsx(Play, { className: "h-12 w-12 text-white" }) })] }), _jsxs("div", { className: "p-3", children: [_jsx("h3", { className: "font-medium text-gray-900 text-sm line-clamp-2 mb-2", children: post.title }), _jsxs("div", { className: "flex items-center space-x-2 mb-2", children: [_jsx("img", { src: post.creator.avatar, alt: post.creator.name, className: "w-6 h-6 rounded-full", onClick: () => {
                                                    handleCreatorClick(post.creator.display_name);
                                                } }), _jsxs("span", { onClick: () => {
                                                    handleCreatorClick(post.creator.display_name);
                                                }, className: "text-xs text-gray-600 flex items-center", children: [post.creator.name, post.creator.verified && _jsx("span", { className: "text-yellow-500 ml-1", children: "\u2605" })] })] }), _jsxs("div", { className: "flex items-center justify-between text-xs text-gray-500", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsxs("span", { className: "flex items-center", children: [_jsx(Eye, { className: "h-3 w-3 mr-1" }), post.views.toLocaleString()] }), _jsxs("span", { className: "flex items-center", children: [_jsx(Heart, { className: "h-3 w-3 mr-1" }), post.likes.toLocaleString()] })] }), _jsx(Button, { variant: "ghost", size: "sm", className: "h-6 px-2", children: _jsx(Bookmark, { className: "h-3 w-3" }) })] })] })] }, post.id))) })] }) }));
}
