import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Home, Rss, TrendingUp, MessageCircle, User } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/providers/AuthContext';
export default function BottomNavigation() {
    const navigate = useNavigate();
    const { user } = useAuth();
    return (_jsx("nav", { className: "fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 z-50", children: _jsx("div", { className: "max-w-7xl mx-auto px-4", children: _jsxs("div", { className: "flex items-center justify-around py-2 px-4", children: [_jsxs("div", { className: "flex flex-col items-center py-2 text-primary cursor-pointer w-16", onClick: () => navigate('/'), children: [_jsx(Home, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs mt-1 font-medium text-center", children: "\u30DB\u30FC\u30E0" })] }), _jsxs("div", { className: "flex flex-col items-center py-2 text-gray-500 hover:text-primary cursor-pointer w-16", onClick: () => navigate('/feed'), children: [_jsx(Rss, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs mt-1 text-center", children: "\u30AB\u30C6\u30B4\u30EA" })] }), _jsxs("div", { className: "flex flex-col items-center py-2 text-gray-500 hover:text-primary cursor-pointer w-16", onClick: () => navigate('/share/post'), children: [_jsx(TrendingUp, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs mt-1 text-center", children: "\u6295\u7A3F" })] }), _jsxs("div", { className: "flex flex-col items-center py-2 text-gray-500 hover:text-primary cursor-pointer w-16", onClick: () => navigate('/ranking/posts'), children: [_jsx(MessageCircle, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs mt-1 text-center", children: "\u30E9\u30F3\u30AD\u30F3\u30B0" })] }), _jsxs("div", { className: "flex flex-col items-center py-2 text-gray-500 hover:text-primary cursor-pointer w-16", onClick: () => navigate('/account'), children: [_jsx(User, { className: "h-6 w-6" }), _jsx("span", { className: "text-xs mt-1 text-center", children: "\u30A2\u30AB\u30A6\u30F3\u30C8" })] })] }) }) }));
}
